/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'Repair' : IDL.Null,
  'Replacement' : IDL.Null,
  'Gutters' : IDL.Null,
  'Emergency' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const BookingRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
  'dateTime' : IDL.Text,
});
export const QuoteStatus = IDL.Variant({
  'new' : IDL.Null,
  'contacted' : IDL.Null,
});
export const QuoteSubmission = IDL.Record({
  'id' : IDL.Nat,
  'status' : QuoteStatus,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getQuotes' : IDL.Func([], [IDL.Vec(QuoteSubmission)], ['query']),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitQuote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'Repair' : IDL.Null,
    'Replacement' : IDL.Null,
    'Gutters' : IDL.Null,
    'Emergency' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const BookingRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  const QuoteStatus = IDL.Variant({ 'new' : IDL.Null, 'contacted' : IDL.Null });
  const QuoteSubmission = IDL.Record({
    'id' : IDL.Nat,
    'status' : QuoteStatus,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'getQuotes' : IDL.Func([], [IDL.Vec(QuoteSubmission)], ['query']),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitQuote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };