/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRequest {
  'id' : bigint,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'name' : string,
  'email' : string,
  'address' : string,
  'timestamp' : Timestamp,
  'phone' : string,
  'dateTime' : string,
}
export type BookingStatus = { 'pending' : null } |
  { 'confirmed' : null };
export type QuoteStatus = { 'new' : null } |
  { 'contacted' : null };
export interface QuoteSubmission {
  'id' : bigint,
  'status' : QuoteStatus,
  'serviceType' : ServiceType,
  'name' : string,
  'description' : string,
  'email' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export type ServiceType = { 'Repair' : null } |
  { 'Replacement' : null } |
  { 'Gutters' : null } |
  { 'Emergency' : null };
export type Timestamp = bigint;
export interface _SERVICE {
  'getBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getQuotes' : ActorMethod<[], Array<QuoteSubmission>>,
  'submitBooking' : ActorMethod<
    [string, string, string, string, ServiceType, string],
    bigint
  >,
  'submitQuote' : ActorMethod<
    [string, string, string, ServiceType, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];