/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface QuoteSubmission {
    id: bigint;
    status: QuoteStatus;
    serviceType: ServiceType;
    name: string;
    description: string;
    email: string;
    timestamp: Timestamp;
    phone: string;
}
export interface BookingRequest {
    id: bigint;
    status: BookingStatus;
    serviceType: ServiceType;
    name: string;
    email: string;
    address: string;
    timestamp: Timestamp;
    phone: string;
    dateTime: string;
}
export enum BookingStatus {
    pending = "pending",
    confirmed = "confirmed"
}
export enum QuoteStatus {
    new_ = "new",
    contacted = "contacted"
}
export enum ServiceType {
    Repair = "Repair",
    Replacement = "Replacement",
    Gutters = "Gutters",
    Emergency = "Emergency"
}
export interface backendInterface {
    getBookings(): Promise<Array<BookingRequest>>;
    getQuotes(): Promise<Array<QuoteSubmission>>;
    submitBooking(name: string, phone: string, email: string, address: string, serviceType: ServiceType, dateTime: string): Promise<bigint>;
    submitQuote(name: string, phone: string, email: string, serviceType: ServiceType, description: string): Promise<bigint>;
}
import type { BookingRequest as _BookingRequest, BookingStatus as _BookingStatus, QuoteStatus as _QuoteStatus, QuoteSubmission as _QuoteSubmission, ServiceType as _ServiceType, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getBookings(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotes(): Promise<Array<QuoteSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotes();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotes();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ServiceType, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(arg0, arg1, arg2, arg3, to_candid_ServiceType_n13(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(arg0, arg1, arg2, arg3, to_candid_ServiceType_n13(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async submitQuote(arg0: string, arg1: string, arg2: string, arg3: ServiceType, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuote(arg0, arg1, arg2, to_candid_ServiceType_n13(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuote(arg0, arg1, arg2, to_candid_ServiceType_n13(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_BookingRequest_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingRequest): BookingRequest {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_QuoteStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuoteStatus): QuoteStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_QuoteSubmission_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuoteSubmission): QuoteSubmission {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _QuoteStatus;
    serviceType: _ServiceType;
    name: string;
    description: string;
    email: string;
    timestamp: _Timestamp;
    phone: string;
}): {
    id: bigint;
    status: QuoteStatus;
    serviceType: ServiceType;
    name: string;
    description: string;
    email: string;
    timestamp: Timestamp;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_QuoteStatus_n11(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_ServiceType_n6(_uploadFile, _downloadFile, value.serviceType),
        name: value.name,
        description: value.description,
        email: value.email,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    serviceType: _ServiceType;
    name: string;
    email: string;
    address: string;
    timestamp: _Timestamp;
    phone: string;
    dateTime: string;
}): {
    id: bigint;
    status: BookingStatus;
    serviceType: ServiceType;
    name: string;
    email: string;
    address: string;
    timestamp: Timestamp;
    phone: string;
    dateTime: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n4(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_ServiceType_n6(_uploadFile, _downloadFile, value.serviceType),
        name: value.name,
        email: value.email,
        address: value.address,
        timestamp: value.timestamp,
        phone: value.phone,
        dateTime: value.dateTime
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    contacted: null;
}): QuoteStatus {
    return "new" in value ? QuoteStatus.new : "contacted" in value ? QuoteStatus.contacted : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Repair: null;
} | {
    Replacement: null;
} | {
    Gutters: null;
} | {
    Emergency: null;
}): ServiceType {
    return "Repair" in value ? ServiceType.Repair : "Replacement" in value ? ServiceType.Replacement : "Gutters" in value ? ServiceType.Gutters : "Emergency" in value ? ServiceType.Emergency : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingRequest>): Array<BookingRequest> {
    return value.map((x)=>from_candid_BookingRequest_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuoteSubmission>): Array<QuoteSubmission> {
    return value.map((x)=>from_candid_QuoteSubmission_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ServiceType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    Repair: null;
} | {
    Replacement: null;
} | {
    Gutters: null;
} | {
    Emergency: null;
} {
    return value == ServiceType.Repair ? {
        Repair: null
    } : value == ServiceType.Replacement ? {
        Replacement: null
    } : value == ServiceType.Gutters ? {
        Gutters: null
    } : value == ServiceType.Emergency ? {
        Emergency: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
